---
- hosts: all
  gather_facts: true
  become: yes
  become_method: sudo

  vars:
    webapp_image_src_dir: /home/ec2-user/demo/docker/webapp
    nginx_image_src_dir: /home/ec2-user/demo/docker/nginx
    webapp_image_name: webapp-demo
    nginx_image_name: nginx
    ecr_image_tag: 'latest'
    ecr_account_id: '408362812773'

  roles:
    - webapp-demo